on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v3
    - uses: ATiltedTree/setup-rust@v1
      with:
        # In case this fails in the future: "rustc --version" says 1.60.0 to me.
        # So this should work:   rust-version: 1.60.0
        rust-version: stable
    - run: cargo build
    - run: cargo test
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
        components: rustfmt
    - run: git status
    - run: cargo fmt
    - run: git status
    - name: Add, commit, push
      if: github.event_name == 'pull_request'
      run: |
        set -x
        git config user.name github_actions.yml
        git config user.email '<>'
        git add src
        if ! git diff --exit-code; then
          git commit -m "Run cargo fmt"
          git push ${{ github.event.pull_request.head.repo.url }} HEAD:${{ github.event.pull_request.head.ref }}
        fi
    - run: git diff --exit-code
#  clippy:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - uses: ATiltedTree/setup-rust@v1
#      with:
#        rust-version: stable
#        components: clippy
#    - run: cargo clippy -- -D warnings
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm install
    - run: npx eslint web-ui/*.js
