on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - run: cargo check
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - run: cargo fmt --check
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm install
    - run: npx eslint web-ui/*.js
