on:
  push:
    branches:
      - main
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - run: |
          pip install -r requirements-dev.txt
      - run: |
          black --check *.py
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - run: |
          pip install -r requirements-dev.txt
      - run: |
          mypy --python-version 3.7 --strict *.py
          mypy --python-version 3.8 --strict *.py
          mypy --python-version 3.9 --strict *.py
          mypy --python-version 3.10 --strict *.py
  pyflakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - run: |
          pip install -r requirements-dev.txt
      - run: |
          pyflakes *.py
