on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v3
    - uses: ATiltedTree/setup-rust@v1
      with:
        # In case this fails in the future: "rustc --version" says 1.60.0 to me.
        # So this should work:   rust-version: 1.60.0
        rust-version: stable
    - run: cargo build
    - run: cargo test
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # https://github.com/marketplace/actions/add-commit#working-with-prs
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
        components: rustfmt
    - run: cargo fmt
    - if: github.event_name == 'pull_request'
      uses: EndBug/add-and-commit@v9
      with:
        add: src
        default_author: github_actions
    - run: git diff --exit-code
#  clippy:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - uses: ATiltedTree/setup-rust@v1
#      with:
#        rust-version: stable
#        components: clippy
#    - run: cargo clippy -- -D warnings
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm install
    - run: npx eslint web-ui/*.js
