on:
  push:
    branches:
      - main
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - run: pip install -r requirements-dev.txt
      - run: black --check catris/
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - run: pip install -r requirements-dev.txt
      - run: isort --check catris/
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - run: mypy --python-version 3.7 --strict catris/
      - run: mypy --python-version 3.8 --strict catris/
      - run: mypy --python-version 3.9 --strict catris/
      - run: mypy --python-version 3.10 --strict catris/
  pyflakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - run: pip install -r requirements-dev.txt
      - run: pyflakes catris/
