on:
  push:
    branches:
      - main
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - run: |
          python3 -m pip install -r requirements-dev.txt
      - run: |
          python3 -m black --check *.py
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - run: |
          python3 -m pip install -r requirements-dev.txt
      - run: |
          python3 -m mypy --strict *.py
  pyflakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - run: |
          python3 -m pip install -r requirements-dev.txt
      - run: |
          pyflakes *.py
